rails-basics-labs/amazon_application/config/routes.rb
Rails.application.routes.draw do
  get 'admin/panel'
  # get 'sessions/new'
  # get 'users/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resource :session, only:[:new, :create, :destroy]

  resources :users, only: [:new, :create]

  resources :news_articles, only: [:new, :create, :show, :index]
  
  root 'amazon#index' 

  resources :products do
    resource :favourites, shallow: true, only: [:create, :destroy]
    resources :reviews, only: [:create, :destroy] do
      resources :likes, shallow: true, only: [:create, :destroy]
    end
    post '/reviews/:id', to: 'reviews#unhide', as: :review_unhide
  end
  resources :favourites, only: [:index]
  get '/home', to: 'amazon#home'
  get '/about_us', to: 'amazon#about_us', as: "about"
  get '/contact_us', to: 'amazon#contact_us', as: "contact"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      resources :products, only: [:index, :show]
    end
  end

end

rails-basics-labs/amazon_application/app/models/product.rb
class Product < ApplicationRecord
    belongs_to :user
    after_initialize :set_defaults
    before_save :capitalize_title

    has_many :reviews, dependent: :destroy

    has_many :favourites, dependent: :destroy
    has_many :favourite_users, through: :favourites, source: :user

    validates(
        :title,
        presence: true, 
        uniqueness: {
            scope: :title
        }
    )

    validates(
        :price, 
        numericality: {
            greater_or_equal_to: 0 
        }
    )

    validates(
        :description, 
        presence: true,
        length: {
            minimum: 2
        }
    )

    def self.search(str)
        
    end

    private

    def set_defaults
        self.price = 0 if self.price.nil?
    end

    def capitalize_title
        self.title.capitalize!
    end

end

rails-basics-labs/amazon_application/app/controllers/api/v1/products_controller.rb
class Api::V1::ProductsController < Api::ApplicationController
    def index
        products = Product.order(created_at: :desc)
        render(json: products)
    end

    def show 
        product = Product.find(params[:id])
        render(json: product)
    end
end

rails-basics-labs/amazon_application/app/controllers/products_controller.rb
class ProductsController < ApplicationController

    before_action :find_product, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:edit, :update, :destroy]

    def new
        @product = Product.new
    end

    def create
        @product = Product.create(product_params)
        @product.user = current_user

        if @product.save
            flash[:success] = "Question successfully created"
            redirect_to @product
        else
            flash[:error] = "Failed to create"
            render 'new'
        end
    end

    def index
        @products = Product.order(created_at: :desc)
    end

    def show
        @reviews = @product.reviews.order(created_at: :desc)
        @review = Review.new
        @favourite = current_user.favourites.find_by_product_id(@product.id)
        p "******"
        p @favourite
        p "******"
    end

    def edit

    end

    def update
        if @product.update(product_params)
            redirect_to @product, alert: "Successfully Updated"
        else
            flash[:error] = "Failed to update"
            render :edit
        end
    end

    def destroy
        # raise
        @product.destroy
        redirect_to products_path
    end

    # to add in favourites controller 
    # def favourite_products 
    #     @favourites = current_user.favourite_products
    # end

    private

    def find_product
        @product = Product.find params[:id]
    end

    def product_params
        params.require(:product).permit(:title, :description)
    end

    def authorize_user!
        redirect_to root_path, alert: "Not Authorized!" unless can?(:modify, @product)
    end
end

rails-basics-labs/amazon_application/app/helpers/products_helper.rb
module ProductsHelper
end

rails-basics-labs/amazon_application/app/views/products/_form.html.erb
<%= form_with model: @product, local: true do |form| %>
    <div>
        <%= form.label :title %>
        <br>
        <%= form.text_field :title %>
    </div>
    <div>
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, cols:50, rows:5 %>
    </div>
    <%= form.submit("create") %>

    
<% end %>

rails-basics-labs/amazon_application/app/views/products/edit.html.erb
<h1>Edit</h1>

<%= render "form" %>

rails-basics-labs/amazon_application/app/views/products/index.html.erb
<h1>Products Index</h1>

<% @products.each do |product| %>
    <div>
        <h2>
            <%= link_to product.title, product %>
        </h2>
    </div>
<% end %>

rails-basics-labs/amazon_application/app/views/products/new.html.erb
<h1>New</h1>
<small><%= current_user.id %></small>
<%= render "form" %>

rails-basics-labs/amazon_application/app/views/products/show.html.erb
<h1>View Page</h1>

<h2><%= @product.title %> </h2>
<p><%= @product.description %> <small>$<%= (@product.price).round(2) %></small></p>
<div>
    <small>
    Created <%= time_ago_in_words(@product.created_at)%> ago by <%= @product.user.full_name %> 
    </small>
</div>
<% if can? :modify, @product %>
<%= link_to "Edit", edit_product_path(@product.id) %>
<%= button_to "Delete", @product, method: :delete %>
<% end %>
<% if user_signed_in? %>
    <% if @favourite %>
        <%= button_to "Remove from favourite", product_favourites_path(@product.id, @favourite.id), method: :delete %>
    <% else %>
        <%= button_to "Add to favourite", product_favourites_path(@product.id), method: :post %>
    <% end %>
<% end %>
<ul>
    <% @reviews.each do |review| %>
    <li>
        <%= review.body %>
        <small>
        Reviewed <%= time_ago_in_words(review.created_at)%> ago by <%= review.user.full_name %> 
        </small>
        <% if can? :modify, review %>
        <%= button_to("Delete", product_review_path(@product.id, review.id) , method: :delete, data:{confirm:"Are you sure?"}) %>
        <% end %>
        <small>
        <% if user_signed_in? %>
            <% like = current_user.likes.find_by_review_id(review) %>
            <% count = review.likes.count %>

            <% if like %>
                <%= button_to "Unlike", like_path(like), method: :delete %>
                <small><%= count %> Likes</small>
            <% else %>
                <%= button_to "Like", product_review_likes_path(@product, review), method: :post %>
                <small><%= count %> Likes</small>
            <% end %>
        <% end %>
        </small>        
    </li>
    <% end %>
</ul>
<hr>

<h3>Write a review</h3>
<% if @review.errors.any? %>
    <% @review.errors.full_messages.each do |msg| %>
      <small> <%= msg %></small>
    <% end %> 
<% end %>

<%= form_with(model: [@product, @review]) do |f| %>
    <div>
        <%= f.label :body %>
        <br>
        <%= f.text_area :body, cols: 50, rows: 5 %>
    </div>
    <%= f.submit "Review" %>
<% end %>