rails_projects/awesome_answers/config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'

  # if you dont need the :id in the routes, then use "resource" not "resources"
  resource :session, only:[:new, :create, :destroy]
  # 'resource' is singular instead of 'resources'
  # Unlike 'resources', 'resource' will create routes that do CRUD operations
  # on only one thing. Also there will be no index routes, and no route
  # will have an ':id' wildcard. But the controller name is still plural

  resources :users, only: [:new, :create, :show]
  # get 'users/new'
  # get 'users/create'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # ------------------------RESTful Routes----------------------------------
  # A RESTful route provides mapping from HTTP verbs (like GET, POST, PATCH, PUT, DELETE)
  # to the controller CRUD actions (create, read, update, destroy)

  # RESTful Routes for Questions resource
  # index: GET "/resources" - return all records of that resource
  # show: GET "/resources/:id" returns one instance of the resource
  # new: GET "/resources/new" - return a view page with form the create a resource
  # create: POST "/resources" -handle submission to the "new form" and inserts a new resource in the db
  # edit: GET "/resources/:id/edit" -returns a view to edit an existing resource
  # update: PATCH "/resource/:id" -handle submission of the "edit form" and update the resource with specific id in the db
  # destroy: DELETE "resources/:id" - delete a record with specific id from the database
  #------------------------------------------------------------------------------------

  # new
  # get 'questions/new'

  # create
  # post 'questions', to: 'question#create', as: :create_question

  # index
  # get 'questions', to: 'question#index'

  # show
  # get 'questions/:id', to: 'questions#show', as: :question

  # edit
  # get 'questions/:id/edit', to: 'questions#edit', as: :edit_question

  # update
  # patch 'questions/:id', to: 'questions#update'

  # destroy
  # delete 'questions/:id', to: 'question#destroy', as: :delete_question

  resources :questions do
    # Routes written inside of a block passed a resource method will be prefixed 
    # by a path corresponding to the passed in symbol
    # in this case, all nested routes will be prefixed with 'questions/:question_id'

    # post 'questions', to: 'questions#create', as: :create_question
    # /questions method post
    # /questions/:question_id/answers method post
    resources :answers, only: [:create, :destroy]
    # resources :answers, except: [:show, :new, :index, :edit, :update]

    resources :likes, shallow: true,  only: [:create, :destroy]
    #shallow: true changes the PATH of the created route
    #original route /question/:question_id/likes/:like_id
    #route with shallow: true -> likes/:like_id

    get :liked, on: :collection
    #the above route creates a path like: GET "/questions/liked"
    #similar to the questions index, but it will only show the questions liked by the current user
  end
  # ^^ this generates all the RESTful routes that CRUD requires for us
  # make sure to check /rails/info/routes

  # Testing
  resources :job_posts, only: [:new, :create, :show, :index, :edit, :update, :destroy]

  # Defines the root path route ("/")
  # root "articles#index"

  # When users type "localhost:3000" 
  # it sends a http get request to this path "localhost:3000", 
  # which is rails' default server when running "rails s"
  # The http get request will be handled by the "WelcomeController" in the "index" action

  # get('/', {to: 'welcome#index'})
  root "welcome#index" #root can be used to indicated the default root page, same as the request above

  get "/welcome", to: "welcome#index"

  get "/goodbye", to: "welcome#goodbye", as: :what #:as option give you the ability to give an alias to a specific path

  # when directing a route in a view page, you give it a path to access the route: 
  #(see views/layouts/application.html.erb for the navigation paths as examples)
  # goodbye_url => http://localhost:3000/goodbye
  # goodbye_path => /goodbye

  #to see all the paths, aliases, verbs, and controller#action's associated with each other,
  #go to the following in the browser: http://localhost:3000/rails/info/routes

  get "form_example", to: "welcome#form_example"

  # get('/question/:id') #dynamic id's will replace :id with the number or params given in url

  resources :likes, shallow: true, only: [:create, :destroy]

  # get :liked, on: :collection

  #Delayed_job routes:
  #We will see this route at this url: 'localhost:3000/delayed_job/overview'
  match(
    "delayed_job",
    to: DelayedJobWeb,
    anchor: false,
    via: [:get, :post]
  )

  #=======================API ROUTES===============>
  #The namespace method in Rails makes it so that your app will automatically
  #look in a directory called api, then in a sub directory called v1 for QuestionsController
  #api/v1/questions

  #The option 'defaults: {format: :json } will set json as the default response 
  #format for all routes contained within the block
  
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :questions, only: [:index, :show, :create, :update, :destroy]
      resource :session, only: [:create, :destroy]
      resources :users, only: [:create] do
        # get('users/current', {to: "users#current"})
        get :current, on: :collection # api/v1/users/current
      end
    end
    # localhost:3000/api/v1/questions

    # namespace :v2 do
    #   resources :questions
    # end
    match "*unmatched_route", to:"application#not_found", via: :all
  end

  get "/auth/github", as: :sign_in_with_github
  get "auth/:provider/callback", to: "callbacks#index"
  #note that :provider is dynamic, which will be replaced with the provider used to sign in, so this
  #route could be used for multiple third party sign in s with omniauth

end

rails_projects/awesome_answers/app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::ApplicationController
    # this controller is generated by rails g controller api/v1/questions --no-assets --no-helper --skip-template-engine
    # also remember to change the parent class => Api::ApplicationController

    before_action :authenticate_user!, except: [:index, :show]

    rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

    rescue_from ActiveRecord::RecordInvalid, with: :record_invalid

    def index
        questions = Question.order(created_at: :desc)
        # render(json: questions)
        #If the serializer name does not match the model (like questions_serializer matches question.rb)
        #then we need to specify in the specific controller actions which serializer to use
        #with the methos "each_serializer"
        render(json: questions, each_serializer: QuestionCollectionSerializer)
        # we will provide 'each_serializer' named argument to the option hash of the render method that tells which serializer to use with each instance
    end

    #=====POSTMAN index====>
    #name: questions#index
    #request: GET -> http://localhost:3000/api/v1/questions
    #================>

    def show
        question = Question.find(params[:id])
        render(json: question)
        # because question model matches with question serializer, we don't need to 
        #specify which serializer to use like we do above with index and QuestionCollectionSerializer
        # render(json: question, each_serializer: QuestionSerializer)
    end

    #=====POSTMAN show====>
    #name: questions#show
    #request: GET -> http://localhost:3000/api/v1/questions/:id
    #Params: key: id, value: 326 (or any value that exists in your database)
    #================>

    def create
        question = Question.new(question_params)
        # question.user = User.first #hard code user for now
        question.user = current_user
        # if question.save
        #     render json: { id: question.id }
        # else
        #     render(
        #         json: {errors: question.errors.messages },
        #         status: 422 #unprocessable entity HTTP status code
        #     )
        # end

        question.save!
        render json:{id: question.id}
    end

    #=====POSTMAN create====>
    #name: questions#create
    #request: POST -> http://localhost:3000/api/v1/questions
    #Headers: key: Content-Type, value: application/json
    #Body: raw, JSON
    #Example question: {"question": {"title":"New unique question!", "body":"This is a newly created question" }}
    #**Remember, this will only work if a user is hard coded, or if session has been created
    #================>

    def update
        question = Question.find(params[:id])
        if question.update(question_params)
            render json: {id: question.id }
        else
            render(
                json: { errors: question.errors.messages },
                status: 422
            )
        end
    end
    #=====POSTMAN update====>
    #name: questions#update
    #request: PATCH -> http://localhost:3000/api/v1/questions/:id
    #Params: key: id, value: 326 (or any value that exists in your database)
    #Headers: key: Content-Type, value: application/json
    #Body: raw, JSON
    #Example question update: {"title": "Title is now updated", "body": "Body is also updated"}
    #**Remember, this will only work if a user is hard coded, or if session has been created
    #================>

    def destroy
        question = Question.find(params[:id])
        if question.destroy
            # head :ok
            render(
                json: { status: 200 }
            )
        else
            # head :bad_request
            render( json: {status: 500})
        end
    end
    #=====POSTMAN destroy====>
    #name: questions#destroy
    #request: DELETE -> http://localhost:3000/api/v1/questions/:id
    #Params: key: id, value: 326 (or any value that exists in your database)
    #**Remember, this will only work if a user is hard coded, or if session has been created
    #================>

    private

    def question_params
        params.require(:question).permit(:title, :body, :tag_names)
    end

    protected

    #protected is like private except that it prevents
    #decendent classes from using the protected methods

    def record_not_found(error)
        render(
            status: 404, #alias :not_found
            json: {
                errors: [
                    {
                        type: error.class.to_s,
                        message: error.message
                    }
                ]
            }
        )
    end

    def record_invalid(error)
        invalid_record = error.record
        errors = invalid_record.errors.map do |errorObject|
            {
                type: invalid_record.class.to_s,
                field: errorObject.attribute,
                message: errorObject.options[:message]
            }
        end
        render(
            json: { status: 422, errors: errors },
            status: 422 #alias :unprocessable_entity
        )
    end


end

rails_projects/awesome_answers/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # To create this controller:
  # rails g controller questions --no-helper --no-assets
  # if you don't need helper.rb and questions.scss files
  # you can add those options when you run rails g controller
  # If you want to configure it so these files are not created by default,
  # you can configure it in config/application.rb

  # ===============CALLBACKS====================
  before_action :find_question, only: [:edit, :update, :show, :destroy]

  before_action :authenticate_user!, except: [:index, :show]

  before_action :authorize_user!, only:[:edit, :update, :destroy]

  # ===============CREATE========================
  def new
    # Because Rails form helper methods need an instance of a model to work, we create a new instance
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      flash[:success] = "Question successfully created"
      redirect_to @question
      # redirect_to question_path(@question)
      # ^^older syntax
    else
      flash[:error] = "Something went wrong"
      render 'new'
    end
  end

  # ============================READ=======================================
  def index
    # @questions = Question.order(created_at: :desc)
    # Model.all is a method built into active record used to return all records of that model
    # the @ sign is necessary to make a variable an instance variable
    # You need instance variables to make it available in the view pages!!!

    if params[:tag]
      @tag = Tag.find_or_initialize_by(name: params[:tag])
      @questions = @tag.questions.order(updated_at: :desc)
    else
      @questions = Question.order(created_at: :desc)
      respond_to do |format|
        format.html { render }
        format.json {render json: @questions}
      end
    end
  end

  def show
    @answers = @question.answers.order(created_at: :desc)
    @answer = Answer.new
    @like = @question.likes.find_by(user: current_user)
    #@like = Like.find_by(question: @question, user: current_user)
    #We use the likes of the @question to see if there is arecord that user_id is the current_user
    #if there is a record, @like is that association
    #id not, @like will be nil
  end

  # ===========================UPDATE=====================================
  def edit
    
  end

  def update
    if @question.update(question_params)
      flash[:success] = "Question successfully updated"
      redirect_to @question
      # redirect_to question_path(@question)
      # ^^older syntax
    else
      flash[:error] = "Something went wrong"
      render :edit
    end
  end

  # ============================DELETE=====================================
  def destroy
    @question.destroy
    redirect_to questions_path
  end

  #This controller acrtion will be used to show all the questions likied by the current user:
  def liked
    @questions = current_user.liked_questions
  end

  private

  def find_question
    @question = Question.find params[:id]
  end
  # ^^ This finds a singular question by getting the :id
  # we end up reusing this line thats why we make it a private method

  # As an added layer of protection to our database,
  # and to prevent malicious SQL injection, we only permit users
  # to inject data for the required params in the form,
  # related to the given model:
  def question_params
    params.require(:question).permit(:title, :body, :tag_names)
    # get the data from the form and add it into the DB
    # Use the 'require' on the params object to retrieve the nested hash of a key
    # usually corresponding the key-value pairs of a form
    # 'permit' to specify all input names are allowed to submit to the DB
  end

  def authorize_user!
    redirect_to root_path, alert: "Not authorized!" unless can?(:crud, @question)
  end
  
  
end

rails_projects/awesome_answers/app/views/questions/_form.html.erb
<%= form_with(model: @question) do |form| %>
  <div>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <br>
    <%= form.text_area :body, cols:50, rows: 5 %>
  </div>
  <div class="tag-wrapper">
    <%= form.label :tag_names %>
    <%= form.text_field :tag_names %>
  </div>
  <%= form.submit %>

<% end %>

<%# selectize docs: https://github.com/selectize/selectize.js/blob/master/docs/usage.md %>

<script>
  $(function(){
    $('#question_tag_names').selectize({
      delimeter: ',',
      persist: false,
      labelField: 'name', //The name of the property to render as an option / item label.
      valueField: 'name', //The name of the property to use as the value when an item is selected.
      searchField: 'name', //An array of property names to analyze when filtering options.
      options: <% Tag.select(:name).to_json(except: [:id]).html_safe %>,
      //The above line selects only names from the tags table and converts them
      //into a json array that can be displayed in the browser. This will be an array of objects
      //without including the tag id's and it makes sure it's in a safe html string
      // options: [{"name": "first tag name"}, {"name": "second tag name"}, etc]
      create: function(input){
        return {
          name: input
        }
      }
    });
  });
</script>

rails_projects/awesome_answers/app/views/questions/_list.html.erb
<% if @tag.present? %>
    <h2>Showing Questions tagged by:
        <span class="badge rounded-pill bg-primary"><%= @tag.name %></span> 
    </h2>
<% end %>
<div>
    <% @questions.each do |question| %>
    <div>
        <h2><%= link_to question.title, question %></h2>
        <%#             older syntax -> question_path(question) %>
        <hr/>
    </div>
    <% end %>
</div>

rails_projects/awesome_answers/app/views/questions/edit.html.erb
<h1>Edit Question Page</h1>

<%= render "form" %>

rails_projects/awesome_answers/app/views/questions/index.html.erb
<h1>Questions Index Page</h1>
<p>I am found in the questions#index controller actions</p>
<p>This will be my route: get('/questions', to: 'questions#index', as: :questions_index)</p>

<h1> All Questions </h1>
<%= render 'list' %>

rails_projects/awesome_answers/app/views/questions/liked.html.erb
<h1>Liked Questions</h1>

<% if @questions.present? %>
    <% @questions.each do |question| %>
    <div>
        <h3> <%= link_to question.title, question_path(question)%> </h3>
    </div>
    <% end %>
<% else %>
    <h3>There are no liked questions.</h3>
<% end %>

rails_projects/awesome_answers/app/views/questions/new.html.erb
<h1>Questions#new</h1>
<p>Find me in app/views/questions/new.html.erb</p>

<h1>Question New Page</h1>

<%= render "form" %>

rails_projects/awesome_answers/app/views/questions/show.html.erb
<h1>Question Show page</h1>
<h2><%= @question.title %></h2>
<p><%= @question.body %></p>
<p><small>Created at: <%= @question.created_at %>, Views: <%= @question.view_count %></small></p>
<small>Created by: <%= @question.user.full_name %></small>
<small>Liked by: <%= @question.likes.count %> users</small>
<% unless @question.tags.empty? %>
  <p>
    Tags:
    <% @question.tags.each do |tag| %>
      <%= link_to( tag.name, questions_path(tag: tag.name),
        class: 'badge rounded-pill bg-primary'
       )%>
    <% end %>
  </p>
<% end %>
<% if can? :crud, @question %>
  <%= button_to 'Edit', edit_question_path(@question), method: :get %>
  <%= button_to 'Delete', question_path(@question), method: :delete, data: {turbo_confirm: "Are you sure?"} %>
<% end %>
<small>
  <% if @like.present? %>
      <%= button_to "Unlike", like_path(@like), method: :delete %>
    <% else %>
      <%= button_to "Like", question_likes_path(@question), method: :post %>
    <% end %>
</small>

<ul>
  <% @answers.each do |answer| %>
    <li>
      <%= answer.body %>
      <small>
        Answered <%= time_ago_in_words(answer.created_at)%> ago by <%= answer.user.full_name %>
      </small>
      <% if can? :crud, answer %>
        <%= link_to "Delete", question_answer_path(@question.id, answer.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
      <% end %>
    </li>
    <br>
  <% end %>
</ul>
<hr>
<h3>Write an answer</h3>
<% if @answer.errors.any? %>
  <ul>
    <% @answer.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %> 
  </ul>
<% end %>

<%= form_with(model:[@question, @answer]) do |f| %>
  <div>
    <%= f.label :body %>
    <br>
    <%= f.text_area :body, cols: 50, rows: 5 %>
  </div>
  <%= f.submit "Answer" %>
<% end %>